import { EN, RU } from "../utils/consts";


export const langPack = {
    [EN]: {
        DOWNLOAD_APP_BTN: 'Download app',
        HOMEPAGE_FAQ_TITLE: 'Most popular questions',
        GENERAL_QUESTIONS: 'General Questions',
        CUSTOMERS_QUESTIONS: 'Customers',
        EXPERTS_QUESTIONS: 'Experts',
        PAYMENTS_QUESTIONS: 'Payments',
        BLOG_TITLE: 'Blog',
        FULL_STORY_BTN: 'Full story',
        OTHER_POSTS: 'Other posts',
        HEADER: {
            HOW_IT_WORKS: 'How it works',
            BECOME_PRO: 'Become a Pro',
            BLOG: 'Blog',
            FAQ: 'FAQ',
            CONTACT: 'Contact us',
        },
        FOOTER: {
            HOME: 'Home',
            CONTACT: 'Contact',
            BLOG: 'Blog',
            POLICY: 'Privacy Policy',
            TERMS: 'Terms',
            FAQ: 'FAQ',
        },
        CONTACT_US: {
            title: 'Contact us',
            subTitle: 'Any questions? Drop us a line.',
            name: 'Your name',
            email: 'Your email',
            company: 'Company',
            subject: 'Subject',
            message: 'Your message',
            success: 'Your message has been sent. Thank you!',
            submitBtn: 'Submit',
        },
        SERVICES: {
            LANGUAGE_PRACTICE: 'Language practice',
            IMMIGRATION_LAW: 'Immigration advice',
            LANGUAGE_LEARNERS: 'Language learning',
        },
        FAQ: 'FAQ',
        MORE_FAQ: 'More FAQ',
    },
    [RU]: {
        DOWNLOAD_APP_BTN: 'Скачать приложение',
        HOMEPAGE_FAQ_TITLE: 'Популярные вопросы',
        GENERAL_QUESTIONS: 'Общие вопросы',
        CUSTOMERS_QUESTIONS: 'Клиенты',
        EXPERTS_QUESTIONS: 'Эксперты',
        PAYMENTS_QUESTIONS: 'Оплата',
        BLOG_TITLE: 'Блог',
        FULL_STORY_BTN: 'Подробнее',
        OTHER_POSTS: 'Другие статьи',
        HEADER: {
            HOW_IT_WORKS: 'O нас',
            BECOME_PRO: '',
            BLOG: 'Блог',
            FAQ: 'Часто задаваемые вопросы',
            CONTACT: 'Связь с нами',
        },
        FOOTER: {
            HOME: 'Главная',
            CONTACT: 'Контакт',
            BLOG: 'Блог',
            POLICY: 'Политика приватности',
            TERMS: 'Условия',
            FAQ: 'ЧаВо',
        },
        CONTACT_US: {
            title: 'Как с нами связаться?',
            subTitle: 'Есть вопросы? Напишите нам.',
            name: 'Ваше имя',
            email: 'Ваш имейл',
            company: 'Название компании',
            subject: 'Тема',
            message: 'Ваше сообщение',
            success: 'Ваше сообщение было отправлено. Спасибо!',
            submitBtn: 'Отправить',
        },
        SERVICES: {
            LANGUAGE_PRACTICE: 'Практика английского',
            IMMIGRATION_LAW: 'Советы по иммиграции',
            LANGUAGE_LEARNERS: 'Изучение языка',
        },
        FAQ: 'Часто задаваемые вопросы',
        MORE_FAQ: 'Больше вопросов',
    }
}